package ee.ioc.phon.android.speak.model;

import io.realm.RealmObject;
import io.realm.annotations.Ignore;
import io.realm.annotations.PrimaryKey;

public class WsServer extends RealmObject {

    @PrimaryKey
    private String uri;

    @Ignore
    private int sessionId;

    // Standard getters & setters generated by your IDE…
    public String getUri() {
        return uri;
    }

    public void setUri(String uri) {
        this.uri = uri;
    }

    public int getSessionId() {
        return sessionId;
    }

    public void setSessionId(int sessionId) {
        this.sessionId = sessionId;
    }

    // TODO: query for the number of slots to find out if the server is working/reliable
}